server:
  port: 9202
service-url:
  user-service: http://localhost:8201
spring:
  cloud:
    gateway:
      routes:
        - id: after_route #路由的ID
          uri: ${service-url.user-service} #匹配后路由地址
          filters:
            - AddRequestParameter=ids,2
          predicates: #断言，路径相匹配的进行路由
#              - Path=/user/getUser/{id}
#            - After=2020-09-07T20:30:00+08:00[Asia/Shanghai]
#            - Cookie=username,dang
            - Method=GET