server:
  port: 8905
spring:
  application:
    name: config-security-server
  cloud:
    config:
      server:
        git: #配置存储配置信息的git仓库
          uri: https://github.com/Dang-dang/SpringCloud-Config.git
          clone-on-start: true #开启启动时直接从git获取配置
  security:
    user:
      name: dang
      password: 123456

