server:
  port: 8801
spring:
  application:
    name: zuul-proxy
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://dang:123456@localhost:8001/eureka/

zuul:
  routes: #给服务配置路由,** 路径为对应服务的请求路径
    user-service:
      path: /userService/**
    feign-service:
      path: /feignService/**
  prefix: /proxy #给网关路由添加前缀
  sensitive-headers: Cookie,Set-Cookie,Authorization #配置过滤敏感的请求头信息，设置为空就不会过滤
  add-host-header: true #设置为true重定向是会添加host请求头
  PreLogFilter: #禁用PreLogFilter过滤器
    pre:
      disable: true


management:
  endpoints:
    web:
      exposure:
        include: 'routes'  #开启查看路由的端点