server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 172.16.80.131
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 1000ms
        max-idle: 8
        min-idle: 0
    timeout: 3000ms
    password: root
  data:
    elasticsearch:
      repositories:
        enabled: true
#这里有个坑，会报 None of the configured nodes are available 异常，
#需要在docker的elasticsearch的配置文件elasticsearch.yml中添加 network.host: 0.0.0.0
# http.host: 0.0.0.0 保证http连接的9200端口正常
# network.host: 0.0.0.0 保证java连接的9300端口正常
      cluster-nodes: 172.16.80.131:9310 #es链接地址及端口
      cluster-name: elasticsearch #es集群的名称
    mongodb:
      database: mall-port
      host: localhost
      port: 27017
  elasticsearch:   #控制台一直报elasticsearch 健康检查失败，加上这个可以解决
    rest:
      uris: ["http://172.16.80.131:9210"]
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /mall
    username: mall
    password: mall
    publisher-confirms: true #如果对异步消息需要回调必须设置为 true

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间

#自定义jwt key
jwt:
  tokenHeader: Authorization #jwt存储的请求头
  secret: asdfghjkl #JWT加密解密使用的密钥
  expiration: 3600 #JWT的过期时间（60*60）
  tokenHead: Bearer #JWT负载中拿到开头

#lombok slf4j 日志级别
logging:
  level:
    root: info
