server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 172.16.80.131
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: 1000ms
        max-idle: 8
        min-idle: 0
    timeout: 3000ms
    password: root


mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml

# 自定义redis key
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
    expire:
      authCode: 120 # 验证码超期时间

#自定义jwt key
jwt:
  tokenHeader: Authorization #jwt存储的请求头
  secret: asdfghjkl #JWT加密解密使用的密钥
  expiration: 3600 #JWT的过期时间（60*60）
  tokenHead: Bearer #JWT负载中拿到开头
