server:
  port: 9305
spring:
  application:
    name: admin-client
#  boot:
#    admin:
#      client:
#        url: http://localhost:9301 #配置admin-server地址
#有注册中心就不需要以上这个admin-server的地址了
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

logging:
  file: admin-client.log #添加开启admin的日志监控

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://dang:123456@localhost:8001/eureka/