server:
  port: 8901
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git: #配置存储配置信息的git仓库
          uri: https://github.com/Dang-dang/SpringCloud-Config.git
#          username:
#          password:
          clone-on-start: true #开启启动时直接从git获取配置
          search-paths: '{application}'
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://dang:123456@localhost:8001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'